### ISSUE TITLE
There was an issue processing the build URL

### ISSUE THREAD

**Issue by ewolz3** [max-arias/pathofgems#1]
nullError: TypeError: Cannot read property 'required_level' of undefined

    in default
    in default
    in ErrorBoundary
    in App

Pastebin URL: https://pastebin.com/sdFhmk4i

**Comment by max-arias** [comment]
Thanks for the report! I'll look into it!

**Comment by max-arias** [comment]
Issue resolved in latest deploy, thanks for the report @ewolz3
