### ISSUE TITLE
Fails to load builds with legacy skill gem names

### ISSUE THREAD

**Issue by ppoelzl** [max-arias/pathofgems#2]
nullError: No skill data in this build

    in default
    in default
    in ErrorBoundary
    in App

Fails to load builds with skill gems that have been renamed at some point.
Example: https://pastebin.com/HDPk4Qyq
Weapon Elemental Damage -> Elemental Damage with Attacks

**Comment by max-arias** [comment]
Thanks for the report! I'll look into it!

**Comment by max-arias** [comment]
Thanks for the report @ppoelzl Issue should be fixed in the latest deploy!
